name: Trigger auto deployment for container-app-3byqdi2j3e5ua

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3byqdi2j3e5ua-AutoDeployTrigger-d0a8324f-c0ed-44c9-9517-8484af71d886.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3BYQDI2J3E5UA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3BYQDI2J3E5UA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3BYQDI2J3E5UA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3BYQDI2J3E5UA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3BYQDI2J3E5UA_REGISTRY_PASSWORD }}
          containerAppName: container-app-3byqdi2j3e5ua
          resourceGroup: appspacesragapp9b7aa22a
          imageToBuild: default/container-app-3byqdi2j3e5ua:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


